language: c
dist: trusty
sudo: required

env:
  - ci_docker=debian:buster-slim ci_distro=debian ci_suite=stretch
  - ci_docker=debian:buster-slim ci_distro=debian ci_suite=stretch ci_configopts="--with-curl"
  - ci_docker=ubuntu:xenial ci_distro=ubuntu ci_suite=xenial
  - ci_docker=ubuntu:bionic ci_distro=ubuntu ci_suite=bionic

script:
  - ci/travis-install.sh
  - ci_parallel=2 ci_sudo=yes ci/travis-build.sh

notifications:
  email: false
