[licenses]
unlicensed = "deny"
copyleft = "allow"
allow = ["Apache-2.0", "Apache-2.0 WITH LLVM-exception", "MIT", "BSD-3-Clause", "BSD-2-Clause", "Unlicense", "Unicode-DFS-2016"]
private = { ignore = true }

[bans]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
